/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.jpaSpringRedflix;

import java.util.Optional;

/**
 *
 * @author alejo
 */
public class Ventana extends javax.swing.JFrame {

    RepositorioUsuario repoU;
    RepositorioSerie repoS;

    private String CRUD = "create";

    public Ventana() {
        initComponents();
        String[] args = {};
        JpaSpringRedflixApplication.runSpringServer(args);

        repoS = Extractor.getBean(RepositorioSerie.class);
        repoU = Extractor.getBean(RepositorioUsuario.class);
    }

    /**
     * Creates new form Ventana
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void añadirUsuarioBD() {
        String us_alias = texto_id.getText();       // asignamos los datos de los textfiels a variables
        String us_nombre = texto_nombre.getText();
        String us_apellido = texto_apellido.getText();
        String us_contraseña = texto_contraseña.getText();
        String us_contraseña2 = texto_contraseña2.getText();
        String us_email = texto_email.getText();
        Long us_celular = Long.parseLong(texto_celular.getText());

        Usuario user = new Usuario();   //creamos una instancia de la clase Usuario, que será el usuario con los datos que ingresamos
        user.setId(us_alias);           // asignamos los valores a el usuario que creamos
        user.setNombre(us_nombre);
        user.setApellido(us_apellido);
        user.setEmail(us_email);
        user.setCelular(us_celular);
        user.setPassword(us_contraseña);
        user.setFecha("1997-04-09");    // asigno una fecha predefenida (string) solo para ahorrar tiempo

        System.out.println("------------------------------");
        System.out.println(user.toString());    //imprimo en consola el objeto usuario
        System.out.println("------------------------------");
        repoU.save(user);
        System.out.println("Usuario \"" + us_alias + "\" agregado con éxito");
        aviso.setText("Usuario \"" + us_alias + "\" agregado con éxito"); // aviso es el nombre de una etiqueta en la ventana, esta la puse para mostrar mensajes de error o etcétera
        System.out.println("------------------------------");

        // con este código establecemos los campos de texto en blanco
        texto_apellido.setText("");
        texto_celular.setText("");
        texto_id.setText("");
        texto_contraseña.setText("");
        texto_contraseña2.setText("");
        texto_email.setText("");
        texto_nombre.setText("");

        out.setText("Detalles de datos ingresados: \n" + user.toString());
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoCRUD = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        label_nombre = new javax.swing.JLabel();
        label_apellido = new javax.swing.JLabel();
        label_contraseña2 = new javax.swing.JLabel();
        texto_nombre = new javax.swing.JTextField();
        texto_apellido = new javax.swing.JTextField();
        texto_contraseña2 = new javax.swing.JTextField();
        texto_id = new javax.swing.JTextField();
        label_alias = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        out = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        b1 = new javax.swing.JRadioButton();
        b2 = new javax.swing.JRadioButton();
        b3 = new javax.swing.JRadioButton();
        b4 = new javax.swing.JRadioButton();
        aviso = new javax.swing.JLabel();
        label_contraseña = new javax.swing.JLabel();
        texto_contraseña = new javax.swing.JTextField();
        texto_email = new javax.swing.JTextField();
        label_email = new javax.swing.JLabel();
        texto_celular = new javax.swing.JTextField();
        label_celular = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        GrupoCRUD.add(b1);
        GrupoCRUD.add(b2);
        GrupoCRUD.add(b3);
        GrupoCRUD.add(b4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD base de datos RedFLix >> Tabla Usuarios");
        setLocation(new java.awt.Point(200, 300));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Aceptar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 100, 110));

        label_nombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label_nombre.setText("Nombre");
        jPanel1.add(label_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 50, -1));

        label_apellido.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label_apellido.setText("Apellido");
        jPanel1.add(label_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, -1));

        label_contraseña2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label_contraseña2.setText("Repetir contraseña");
        jPanel1.add(label_contraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 120, -1));

        texto_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(texto_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 100, -1));

        texto_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_apellidoActionPerformed(evt);
            }
        });
        jPanel1.add(texto_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 100, -1));
        jPanel1.add(texto_contraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 100, -1));

        texto_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_idActionPerformed(evt);
            }
        });
        jPanel1.add(texto_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 100, -1));

        label_alias.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label_alias.setText("Alias (id)");
        jPanel1.add(label_alias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Creación usuario Redflix");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 230, 30));

        out.setColumns(20);
        out.setRows(5);
        out.setText(">> Output <<");
        jScrollPane1.setViewportView(out);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 230, 230));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("CRUD"));

        GrupoCRUD.add(b1);
        b1.setSelected(true);
        b1.setText("Create");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        GrupoCRUD.add(b2);
        b2.setText("Read");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        GrupoCRUD.add(b3);
        b3.setText("Update");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        GrupoCRUD.add(b4);
        b4.setText("Delete");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b2)
                    .addComponent(b1)
                    .addComponent(b4)
                    .addComponent(b3))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(b2))
                            .addComponent(b1))
                        .addGap(17, 17, 17)
                        .addComponent(b4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(b3)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 100, 120));

        aviso.setText(">>");
        jPanel1.add(aviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 230, 20));

        label_contraseña.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label_contraseña.setText("Contraseña");
        jPanel1.add(label_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 80, -1));
        jPanel1.add(texto_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 100, -1));
        jPanel1.add(texto_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 100, -1));

        label_email.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label_email.setText("Email");
        jPanel1.add(label_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 120, -1));

        texto_celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_celularActionPerformed(evt);
            }
        });
        jPanel1.add(texto_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 100, -1));

        label_celular.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label_celular.setText("Celular");
        jPanel1.add(label_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 120, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingreso de datos"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 260, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texto_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_idActionPerformed

    private void texto_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_nombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println(">> Boton OK");        // TODO add your handling code here:
// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
// CREAR
        if ("create".equals(CRUD)) {          // si se seleccionó la opción CREATE
            System.out.println("CRUD CREATE");            // mostramos por consola la acción a realizar
            if (!"".equals(texto_id.getText())) {         // solo si el campo del id no esta vacío, realizamos todo lo demás
                String us_alias = texto_id.getText();
                if (!repoU.existsById(us_alias)) {                          // si no existe el usuario (id) en la tabla usuarios
                    if (!"".equals(texto_nombre.getText())
                            && // si los campos no están vacíos
                            !"".equals(texto_apellido.getText())
                            && !"".equals(texto_email.getText())
                            && !"".equals(texto_celular.getText())
                            && !"".equals(texto_contraseña.getText())
                            && !"".equals(texto_contraseña2.getText())) {

                        añadirUsuarioBD();              //ejecuta el método para agregar usuario

                    } else {
                        aviso.setText("Verifique los datos ingresados");
                        System.out.println("Verifique los datos ingresados");

                    }

                } else {
                    aviso.setText("El usuario " + us_alias + " ya existe");
                    System.out.println("El usuario " + us_alias + " ya existe"); //si el usuario (id) ya existe

                }

            }

        }

// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
// LEER
        if ("read".equals(CRUD)) {
            System.out.println("------------------------------");
            System.out.println("CRUD READ");            // mostramos por consola la acción a realizar
            String us_alias = texto_id.getText();       //definimos una variable con los datos del campo de texto id
            if (repoU.existsById(us_alias)) {           // preguntamos si el id existe en la BD                
                
                Optional<Usuario> consulta = repoU.findById(us_alias);  //creamos un Usuario de tipo Optional
                Usuario provisional;                                    //creamos un usuario de nombre provisional
                
                if(consulta.isPresent()){                               //preguntamos si el valor de "consulta" está presente
                    provisional = consulta.get();                       //asignamos el valor de consulta a provisional, que es una instancia de USuario con los valores extraidos de la tabla usuario en base al id
                    System.out.println(provisional.toString());         // imprimimos los datos del objeto provisional
                    
                    out.setText(provisional.toString());                // imprimo pero en el cajón visual de la ventana
                     System.out.println("------------------------------");
                }
                
            }else{
                
                System.out.println("El id \"" + us_alias + "\" no existe en la base de datos");
                 System.out.println("------------------------------");
            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        CRUD = "create";
        label_alias.setVisible(true);
        texto_id.setVisible(true);
        label_nombre.setVisible(true);
        texto_nombre.setVisible(true);
        label_apellido.setVisible(true);
        texto_apellido.setVisible(true);
        label_contraseña.setVisible(true);
        texto_contraseña.setVisible(true);
        label_contraseña2.setVisible(true);
        texto_contraseña2.setVisible(true);
        label_email.setVisible(true);
        texto_email.setVisible(true);
        label_celular.setVisible(true);
        texto_celular.setVisible(true);

        //System.out.println(CRUD);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        CRUD = "read";
        label_alias.setVisible(true);
        texto_id.setVisible(true);
        label_nombre.setVisible(false);
        texto_nombre.setVisible(false);
        label_apellido.setVisible(false);
        texto_apellido.setVisible(false);
        label_contraseña.setVisible(false);
        texto_contraseña.setVisible(false);
        label_contraseña2.setVisible(false);
        texto_contraseña2.setVisible(false);
        label_email.setVisible(false);
        texto_email.setVisible(false);
        label_celular.setVisible(false);
        texto_celular.setVisible(false);

        //System.out.println(CRUD);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        CRUD = "update";
        //System.out.println(CRUD);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        CRUD = "delete";
        //System.out.println(CRUD);
    }//GEN-LAST:event_b4ActionPerformed

    private void texto_celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_celularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_celularActionPerformed

    private void texto_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_apellidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoCRUD;
    private javax.swing.JLabel aviso;
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.JRadioButton b3;
    private javax.swing.JRadioButton b4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_alias;
    private javax.swing.JLabel label_apellido;
    private javax.swing.JLabel label_celular;
    private javax.swing.JLabel label_contraseña;
    private javax.swing.JLabel label_contraseña2;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JTextArea out;
    private javax.swing.JTextField texto_apellido;
    private javax.swing.JTextField texto_celular;
    private javax.swing.JTextField texto_contraseña;
    private javax.swing.JTextField texto_contraseña2;
    private javax.swing.JTextField texto_email;
    private javax.swing.JTextField texto_id;
    private javax.swing.JTextField texto_nombre;
    // End of variables declaration//GEN-END:variables
}
