/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.jpaSpringRedflix;

import java.util.Optional;

/**
 *
 * @author alejo
 */
public class Ventana extends javax.swing.JFrame {

    RepositorioUsuario repoU;
    RepositorioSerie repoS;

    private String CRUD = "";

    public Ventana() {
        initComponents();
        String[] args = {};
        JpaSpringRedflixApplication.runSpringServer(args);

        repoS = Extractor.getBean(RepositorioSerie.class);

    }

    /**
     * Creates new form Ventana
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoCRUD = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        texto_titulo = new javax.swing.JTextField();
        texto_temporadas = new javax.swing.JTextField();
        texto_capitulos = new javax.swing.JTextField();
        texto_id = new javax.swing.JTextField();
        label_id = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        b1 = new javax.swing.JRadioButton();
        b2 = new javax.swing.JRadioButton();
        b3 = new javax.swing.JRadioButton();
        b4 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        aviso = new javax.swing.JLabel();

        GrupoCRUD.add(b1);
        GrupoCRUD.add(b2);
        GrupoCRUD.add(b3);
        GrupoCRUD.add(b4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD base de datos RedFLix >> Tabla Usuarios");
        setLocation(new java.awt.Point(200, 300));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("OK");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 120, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Titulo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("N° Temp");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("N° Cap");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        texto_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_tituloActionPerformed(evt);
            }
        });
        jPanel1.add(texto_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 80, -1));
        jPanel1.add(texto_temporadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 80, -1));
        jPanel1.add(texto_capitulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 80, -1));

        texto_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_idActionPerformed(evt);
            }
        });
        jPanel1.add(texto_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 80, -1));

        label_id.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label_id.setText("Id");
        jPanel1.add(label_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 30, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("CRUD RedFlix Mintic2021");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 230, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(">> Output <<");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 220, 210));

        GrupoCRUD.add(b1);
        b1.setText("Create");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        GrupoCRUD.add(b2);
        b2.setText("Read");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        GrupoCRUD.add(b3);
        b3.setText("Update");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        GrupoCRUD.add(b4);
        b4.setText("Delete");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("CRUD"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 120, 120));
        jPanel1.add(aviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 180, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texto_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_idActionPerformed

    private void texto_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_tituloActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println(CRUD);
        System.out.println("OK");        // TODO add your handling code here:

        //Serie serieTemporal = new Serie();
        //repo.save(serieTemporal);
        //Verificar si los textfields estan vacíos
        if ("".equals(texto_id.getText()) && "".equals(texto_titulo.getText()) && "".equals(texto_temporadas.getText()) && "".equals(texto_capitulos.getText())) {
            //si todos los textfields están vacíos, muestra un mensaje
            aviso.setText("INGRESE DATOS");
        }

//CREATE        
        if ("create".equals(CRUD)) {           // si seleccionó la opción CREATE
            // si no hay texto en el Campo id o esta vacío
            if (false) {
                //no hace nada
                System.out.println(">> id null or empty");
            } else {
                // si hay texto en el Campo id, lo convierte a entero y verifica el id en la BD
                Integer idX = Integer.parseInt(texto_id.getText());
                System.out.println("verificando id " + idX + "...");   //imprime en consola un mensaje anunciando que esta verificando el titulo de la serie en la base de datos
                Optional<Serie> serieIngresada = repoS.findById(idX);   //creamos un optional de tipo Serie 
                
                // pregunta si está presente en la base de datos
                if (serieIngresada.isPresent()) {
                    // si está presente, imprime un mensaje
                    System.out.println(">> " + idX + " ya existe - Ninguna modificación hecha");

                } else { // si no está presente en la DB  
                    //verificamos si hay algun campo vacío
                    if ("".equals(texto_id.getText()) || "".equals(texto_titulo.getText()) || "".equals(texto_temporadas.getText()) || "".equals(texto_capitulos.getText())) {
                        //si alguno de los textfields está vacío, muestra un mensaje
                        aviso.setText("INGRESE LOS DATOS NECESARIOS");
                        
                    } else {
                        //si todos los datos necesarios estan correctamente ingresados, se agrega a la base de datos

                        String tituloIngresar = texto_titulo.getText();
                        Integer temporadasIngresar = Integer.parseInt(texto_temporadas.getText());
                        Integer capitulosIngresar = Integer.parseInt(texto_capitulos.getText());

                        Serie serieIngresar = new Serie(tituloIngresar, capitulosIngresar, temporadasIngresar);
                        repoS.save(serieIngresar);

                    }

                }

            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        CRUD = "create";
        texto_id.setVisible(false);
        label_id.setVisible(false);
        //System.out.println(CRUD);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        CRUD = "read";
        //System.out.println(CRUD);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        CRUD = "update";
        //System.out.println(CRUD);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        CRUD = "delete";
        //System.out.println(CRUD);
    }//GEN-LAST:event_b4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoCRUD;
    private javax.swing.JLabel aviso;
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.JRadioButton b3;
    private javax.swing.JRadioButton b4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel label_id;
    private javax.swing.JTextField texto_capitulos;
    private javax.swing.JTextField texto_id;
    private javax.swing.JTextField texto_temporadas;
    private javax.swing.JTextField texto_titulo;
    // End of variables declaration//GEN-END:variables
}
